"""Initial Schema

Revision ID: 2e3f2ef5d396
Revises: 
Create Date: 2026-07-24 11:40:38.565997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3f2ef5d396'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=True),
    sa.Column('anonymised_label', sa.String(), nullable=False),
    sa.Column('site_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('consent_status', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('audit_logs',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('comparison_results',
    sa.Column('comparison_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('baseline_kwh', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('group_average_kwh', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ratio', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('status_flag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('comparison_id')
    )
    op.create_table('smart_controller_channels',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('controller_channel', sa.String(), nullable=False),
    sa.Column('device_category', sa.String(), nullable=True),
    sa.Column('rated_power_kw', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('switching_state', sa.String(), nullable=False),
    sa.CheckConstraint("controller_channel IN ('geyser', 'fridge', 'lighting', 'plugs', 'cooking', 'background')", name='ck_channel_controller_channel_valid'),
    sa.CheckConstraint("switching_state IN ('on', 'off', 'standby', 'fault')", name='ck_channel_switching_state_valid'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('daily_summaries',
    sa.Column('summary_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_kwh', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('peak_power_kw', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['smart_controller_channels.device_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_table('readings',
    sa.Column('reading_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voltage_v', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('current_a', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('power_kw', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('energy_kwh_interval', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('cumulative_energy_kwh', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('switching_state', sa.String(), nullable=False),
    sa.Column('quality_flag', sa.String(), nullable=False),
    sa.CheckConstraint("quality_flag IN ('valid', 'missing', 'duplicate', 'out_of_range', 'abnormal_event')", name='ck_reading_quality_flag_valid'),
    sa.CheckConstraint("switching_state IN ('on', 'off', 'standby', 'fault')", name='ck_reading_switching_state_valid'),
    sa.ForeignKeyConstraint(['device_id'], ['smart_controller_channels.device_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    op.drop_table('daily_summaries')
    op.drop_table('smart_controller_channels')
    op.drop_table('comparison_results')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('sites')
    # ### end Alembic commands ###
